CREATE TABLE AUTHOR (
AU_ID INT PRIMARY KEY NOT NULL,
AU_FNAME VARCHAR(20) NOT NULL,
AU_LNAME VARCHAR(20) NOT NULL,
AU_BIRTHYEAR INT NOT NULL); 


INSERT INTO AUTHOR VALUES(362, 'Xia', 'Chiang', 1928 );
INSERT INTO AUTHOR VALUES (351, 'Hugo', 'Bruer', 1972);
INSERT INTO AUTHOR VALUES (438, 'Perry', 'Pearson', 1986);
INSERT INTO AUTHOR VALUES (513, 'Julia', 'Palca', 1988);