CREATE TABLE PATRON (
PAT_ID INT PRIMARY KEY NOT NULL,
PAT_FNAME VARCHAR(15) NOT NULL,
PAT_LNAME VARCHAR(15) NOT NULL,
PAT_TYPE VARCHAR(15) NOT NULL);



INSERT INTO PATRON VALUES (2272, 'Lidia', 'Yanes', 'STUDENT');
INSERT INTO PATRON VALUES (2407, 'Iva', 'Ramos', 'Student');
INSERT INTO PATRON VALUES (2429, 'Claudia', 'Yanes', 'Student');
INSERT INTO PATRON VALUES (2283, 'Helena', 'Hughes', 'Faculty');
